url=https://testautomationpractice.blogspot.com

browser=chrome

headless=false

implicit.wait=10

explicit.wait=15

page.load.timeout=30

date.picker.value=06/08/2026

slider.target.value=50

upload.file.path=src/test/resources/testdata.txt